import type { ReactNode } from "react";
import { KeyRound, Plus } from "lucide-react";
import type { AppView, NavigationItem } from "../app/routes";
import { formatCompact, formatCurrency } from "../lib/format";

type UsageSummary = { todayInputTokens?: number; todayOutputTokens?: number; todaySpent?: number; todayLimit?: number; totalSpent?: number; totalLimit?: number };

export function AppSidebar({ view, navigation, usage, usageScope, canAddStation = true, onScopeChange, onNavigate, onAddStation }: { view: AppView; navigation: readonly NavigationItem[]; usage: UsageSummary; usageScope: "all" | "current"; canAddStation?: boolean; onScopeChange: (scope: "all" | "current") => void; onNavigate: (view: AppView) => void; onAddStation: () => void }) {
  return <aside className="app-sidebar flex w-56 shrink-0 flex-col px-4 py-4"><div className="mb-5 flex items-center gap-3 px-2"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-fuchsia-400 to-violet-500 text-white shadow-sm"><KeyRound size={19} /></div></div><div className="flex items-center gap-1.5"><p className="text-lg font-semibold">RelayHub</p></div></div><nav className="space-y-1">{canAddStation && <button className="button-primary h-8 w-full" onClick={onAddStation}><Plus size={16} />添加站点</button>}{navigation.map(({ view: itemView, label, Icon }) => <Nav key={itemView} active={view === itemView} icon={<Icon size={16} />} label={label} onClick={() => onNavigate(itemView)} />)}</nav><SidebarStats usage={usage} scope={usageScope} onScopeChange={onScopeChange} /></aside>;
}

function Nav({ active, icon, label, onClick }: { active: boolean; icon: ReactNode; label: string; onClick: () => void }) { return <button className={`nav-item ${active ? "nav-item-active" : ""}`} onClick={onClick}>{icon}<span className="nav-label">{label}</span></button>; }
function SidebarStats({ usage, scope, onScopeChange }: { usage: UsageSummary; scope: "all" | "current"; onScopeChange: (scope: "all" | "current") => void }) { const tokens = usage.todayInputTokens == null && usage.todayOutputTokens == null ? undefined : (usage.todayInputTokens ?? 0) + (usage.todayOutputTokens ?? 0); return <div className="sidebar-stats"><div className="sidebar-stat-tabs" role="tablist" aria-label="用量范围"><button className={scope === "all" ? "sidebar-stat-tab active" : "sidebar-stat-tab"} onClick={() => onScopeChange("all")} role="tab" aria-selected={scope === "all"}>全部</button><button className={scope === "current" ? "sidebar-stat-tab active" : "sidebar-stat-tab"} onClick={() => onScopeChange("current")} role="tab" aria-selected={scope === "current"}>当前站点</button></div><SidebarStat label="今日 Token" value={formatCompact(tokens)} detail={`输入: ${formatCompact(usage.todayInputTokens)} / 输出: ${formatCompact(usage.todayOutputTokens)}`} /><SidebarStat label="今日消费" value={`${formatCurrency(usage.todaySpent)} / ${formatCurrency(usage.todayLimit)}`} detail={`总计: ${formatCurrency(usage.totalSpent)} / ${formatCurrency(usage.totalLimit)}`} /></div>; }
function SidebarStat({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="sidebar-stat"><p>{label}</p><strong>{value}</strong><span>{detail}</span></div>; }
