import { Play, Search } from "lucide-react";
import { Button } from "../../../components/ui";
import type { ModelTestResult, ProviderDoctorReport } from "../types";
import { formatCost, formatDuration, formatNumber } from "../utils";

export function DetectionDiagnostics({ selected, selectedCount, doctor, doctorRunning, batchResults, batchRunning, batchMode, onBatchModeChange, onDoctor, onBatch }: { selected: boolean; selectedCount: number; doctor?: ProviderDoctorReport; doctorRunning: boolean; batchResults?: ModelTestResult[]; batchRunning: boolean; batchMode: "chat" | "responses"; onBatchModeChange: (mode: "chat" | "responses") => void; onDoctor: () => void; onBatch: () => void }) {
  if (!selected) return null;
  return <>
    <section className="api-detection-model-matrix" aria-live="polite"><div><h2>站点体检</h2><p>检查认证、站点快照、余额/用量、密钥与用量分页接口，以及适配器能力。</p></div><Button variant="secondary" disabled={doctorRunning} onClick={onDoctor}><Search size={16} />{doctorRunning ? "体检中" : "运行体检"}</Button>{doctor && <DoctorTable report={doctor} />}</section>
    <section className="api-detection-model-matrix" aria-live="polite"><div><h2>批量模型测试</h2><p>已选 {selectedCount} 个模型；并发运行短 {batchMode === "chat" ? "Chat" : "Responses"} 探针。</p></div><div className="test-mode-tabs" role="group" aria-label="模型测试协议"><Button variant="test" className={batchMode === "chat" ? "active" : ""} onClick={() => onBatchModeChange("chat")} aria-pressed={batchMode === "chat"}>Chat</Button><Button variant="test" className={batchMode === "responses" ? "active" : ""} onClick={() => onBatchModeChange("responses")} aria-pressed={batchMode === "responses"}>Responses</Button></div><Button variant="secondary" disabled={batchRunning || !selectedCount} onClick={onBatch}><Play size={16} />{batchRunning ? "测试中" : "测试所选模型"}</Button>{batchResults && <BatchTable results={batchResults} />}</section>
  </>;
}

function DoctorTable({ report }: { report: ProviderDoctorReport }) { return <div className="api-detection-model-matrix-results"><div className="mb-3 flex items-center justify-between text-sm"><strong>{report.stationName}</strong><span>{report.healthy ? "状态正常" : "需要处理"} · {formatDuration(report.elapsedMs)}</span></div><table><thead><tr><th>检查项</th><th>状态</th><th>耗时</th><th>详情与建议</th></tr></thead><tbody>{report.checks.map((check) => <tr key={check.id}><td>{check.name}</td><td>{check.status === "pass" ? "通过" : check.status === "warning" ? "警告" : check.status === "skipped" ? "跳过" : "失败"}</td><td>{formatDuration(check.elapsedMs)}</td><td>{check.detail}{check.remediation && <small className="block text-slate-500">{check.remediation}</small>}</td></tr>)}</tbody></table></div>; }
function BatchTable({ results }: { results: ModelTestResult[] }) { return <div className="api-detection-model-matrix-results"><table><thead><tr><th>模型</th><th>协议</th><th>可用性</th><th>总延迟</th><th>首 Token</th><th>Tokens/秒</th><th>用量</th><th>费用</th></tr></thead><tbody>{results.map((item) => <tr key={item.model}><td title={item.error}>{item.model}</td><td>{item.protocol}</td><td>{item.available ? "可用" : "失败"}</td><td>{formatDuration(item.elapsedMs)}</td><td>{item.firstTokenMs === undefined ? "-" : formatDuration(item.firstTokenMs)}</td><td>{item.tokensPerSecond === undefined ? "-" : item.tokensPerSecond.toFixed(1)}</td><td>{formatNumber(item.inputTokens ?? 0)} / {formatNumber(item.outputTokens ?? 0)}</td><td>{formatCost(item.cost)}</td></tr>)}</tbody></table></div>; }
