import type { FormEventHandler } from "react";
import { CheckCircle2, Eye, EyeOff, KeyRound, Play, RefreshCw, Search } from "lucide-react";
import { Button, IconButton, List, SelectField, TextField } from "../../../components/ui";
import type { DetectionProgress, SavedApiKeyRow } from "../types";
import { modelOptions } from "../utils";

export function DetectionConfigForm({ keyRows, savedKeyId, endpoint, apiKey, showKey, selectedSavedKey, availableModels, selectedModels, discoveryError, discoveryFromCache, discoveredCount, discoveryRunning, running, progress, onSubmit, onSavedKeyChange, onEndpointChange, onApiKeyChange, onShowKeyChange, onRefreshModels, onToggleModel }: { keyRows: SavedApiKeyRow[]; savedKeyId: string; endpoint: string; apiKey: string; showKey: boolean; selectedSavedKey: SavedApiKeyRow | undefined; availableModels: string[]; selectedModels: string[]; discoveryError?: string; discoveryFromCache: boolean; discoveredCount?: number; discoveryRunning: boolean; running: boolean; progress?: DetectionProgress; onSubmit: FormEventHandler<HTMLFormElement>; onSavedKeyChange: (value: string) => void; onEndpointChange: (value: string) => void; onApiKeyChange: (value: string) => void; onShowKeyChange: () => void; onRefreshModels: () => void; onToggleModel: (value: string) => void }) {
  return <form className="api-detection-config" onSubmit={onSubmit}>
    <div className="api-detection-config-header"><div><h2>接口配置</h2><p>API Key 只用于本次检测请求，不会保存到本地。</p></div></div>
    <div className="api-detection-fields"><label className="api-detection-saved-key"><span>使用本项目 API Key</span><SelectField className={savedKeyId ? undefined : "placeholder"} value={savedKeyId} onChange={(event) => onSavedKeyChange(event.target.value)} disabled={running}><option value="">手动填写临时 API Key</option>{keyRows.map((row) => <option key={`${row.stationId}-${row.key.id}`} value={`${row.stationId}-${row.key.id}`}>{row.stationName} / {row.key.name || "未命名密钥"} / {row.key.maskedKey}</option>)}</SelectField></label><label><span>API 接口地址</span><div className="api-detection-input"><Search size={16} /><TextField value={endpoint} onChange={(event) => onEndpointChange(event.target.value)} placeholder="https://api.anthropic.com" inputMode="url" autoComplete="url" disabled={running} /></div></label><label><span>API Key</span><div className="api-detection-input key-input"><KeyRound size={16} /><TextField type={showKey ? "text" : "password"} value={apiKey} onChange={(event) => onApiKeyChange(event.target.value)} placeholder={selectedSavedKey ? "将从安全存储按需读取" : "sk-..."} autoComplete="off" disabled={running || Boolean(selectedSavedKey)} /><IconButton label={showKey ? "隐藏 API Key" : "显示 API Key"} onClick={onShowKeyChange} disabled={running || Boolean(selectedSavedKey)} icon={showKey ? <EyeOff size={16} /> : <Eye size={16} />} /></div></label></div>
    <div className="api-detection-models"><div className="api-detection-model-label"><span>目标模型</span>{selectedSavedKey && <IconButton label="刷新模型列表" onClick={onRefreshModels} disabled={running || discoveryRunning} icon={<RefreshCw size={16} className={discoveryRunning ? "animate-spin" : undefined} />} />}</div><List className="api-detection-model-grid" role="group" aria-label="Target models">{availableModels.map((value) => { const option = modelOptions.find((item) => item.value === value); const selected = selectedModels.includes(value); return <Button variant="ghost" type="button" key={value} className={`${selected ? "selected " : ""}${option?.isNew ? "has-new" : ""}`} onClick={() => onToggleModel(value)} aria-pressed={selected} disabled={running}>{option?.isNew && <span className="api-detection-model-new">NEW</span>}<strong>{option?.label ?? value}</strong><small>{value}</small>{selected && <CheckCircle2 size={15} />}</Button>; })}</List>{savedKeyId && <p>{discoveryError ? `模型自动发现不可用：${discoveryError}` : discoveredCount !== undefined ? `已自动发现 ${discoveredCount} 个模型（${discoveryFromCache ? "来自一小时内缓存" : "刚刚刷新"}）` : "正在发现站点模型…"}</p>}</div>
    {progress && <div className="api-detection-progress" role="status" aria-live="polite"><div><span>{progress.current}</span><b>{progress.completed}/{progress.total}</b></div><i><i style={{ width: `${Math.round((progress.completed / progress.total) * 100)}%` }} /></i></div>}
    <footer className="api-detection-actions"><span>共 16 个检测阶段，路由一致性将重复请求 10 次</span><Button variant="primary" type="submit" disabled={running}><Play size={16} />{running ? "检测中" : "开始检测"}</Button></footer>
  </form>;
}
