//! Stable names exposed to the frontend and external desktop automation.
//! Keep this list in sync with `generate_handler!` in `lib.rs` whenever a
//! command is added or removed.

#[cfg_attr(not(test), allow(dead_code))]
pub const COMMAND_NAMES: &[&str] = &[
    "probe_station",
    "send_station_verification_code",
    "diagnose_station",
    "add_station",
    "register_station_account",
    "import_station_with_code",
    "update_station",
    "list_stations",
    "list_login_profiles",
    "get_login_profile",
    "save_login_profile",
    "delete_login_profile",
    "list_remote_servers",
    "list_remote_sync_logs",
    "cancel_remote_server_operation",
    "install_or_update_remote_codex_command",
    "choose_private_key_file",
    "add_remote_server",
    "update_remote_server",
    "delete_remote_server",
    "test_remote_server",
    "verify_remote_codex_session_command",
    "assign_remote_relay_key",
    "update_remote_relay",
    "refresh_station",
    "reauthenticate_station",
    "clear_station_session",
    "refresh_all",
    "get_sync_progress",
    "cancel_sync",
    "get_snapshot",
    "get_usage_summary",
    "list_usage_logs",
    "refresh_usage_logs",
    "get_history",
    "list_audit_events",
    "rollback_audit_event",
    "list_key_rows",
    "list_account_rows",
    "list_rate_rows",
    "list_station_groups",
    "update_key_group",
    "create_api_key",
    "update_api_key",
    "delete_api_key",
    "reveal_key",
    "apply_api_key_to_codex",
    "get_gateway_status",
    "set_routing_mode",
    "set_gateway_port",
    "start_gateway",
    "stop_gateway",
    "set_active_gateway_route",
    "set_active_gateway_routes",
    "get_gateway_credentials",
    "rotate_gateway_token",
    "import_to_cc_switch",
    "test_api_models",
    "discover_api_models",
    "detect_model_authenticity",
    "delete_station",
    "backup_database",
    "get_cloud_auth_status",
    "cloud_sign_up",
    "cloud_sign_in",
    "cloud_request_password_reset",
    "cloud_complete_password_reset",
    "cloud_sign_out",
    "list_cloud_backups",
    "get_local_cloud_backup_preview",
    "create_cloud_backup",
    "delete_cloud_backup",
    "preview_cloud_backup",
    "restore_cloud_backup",
    "get_active_codex_relay_status",
    "get_codex_integration",
    "set_codex_preserve_official_login",
    "get_mail_oauth_status",
    "save_mail_oauth_config",
    "save_mail_password_config",
    "start_mail_oauth",
    "disconnect_mail_oauth",
    "poll_registration_code",
    "get_alert_policy",
    "save_alert_policy",
    "evaluate_alerts",
    "list_alert_history",
    "get_personal_center_notification_preferences",
    "refresh_personal_center_notification_preferences",
    "save_personal_center_notification_preferences",
    "list_personal_center_memberships",
    "save_personal_center_membership",
    "delete_personal_center_membership",
    "list_personal_center_audit_history",
    "list_personal_center_notifications",
    "publish_personal_center_notification",
    "list_sent_personal_center_notifications",
    "update_personal_center_notification",
    "revoke_personal_center_notification",
    "delete_personal_center_notification",
    "mark_personal_center_notification",
    "get_personal_center_realtime_session",
    "list_personal_center_login_events",
];

#[cfg(test)]
mod tests {
    use super::COMMAND_NAMES;

    #[test]
    fn keeps_the_public_tauri_command_contract_complete() {
        assert_eq!(COMMAND_NAMES.len(), 103);
        assert!(COMMAND_NAMES.contains(&"detect_model_authenticity"));
        assert!(COMMAND_NAMES.contains(&"discover_api_models"));
        assert!(COMMAND_NAMES.contains(&"diagnose_station"));
        assert!(COMMAND_NAMES.contains(&"import_station_with_code"));
        assert!(COMMAND_NAMES.contains(&"send_station_verification_code"));
        assert!(COMMAND_NAMES.contains(&"backup_database"));
        assert!(COMMAND_NAMES.contains(&"create_cloud_backup"));
        assert!(COMMAND_NAMES.contains(&"delete_cloud_backup"));
        assert!(COMMAND_NAMES.contains(&"restore_cloud_backup"));
        assert!(COMMAND_NAMES.contains(&"get_active_codex_relay_status"));
        assert!(COMMAND_NAMES.contains(&"list_audit_events"));
        assert!(COMMAND_NAMES.contains(&"rollback_audit_event"));
        assert!(COMMAND_NAMES.contains(&"list_personal_center_memberships"));
    }
}
