import { useRef } from "react";
import { Columns3, Plus, RefreshCw, Search } from "lucide-react";
import type { Station } from "../../stations";
import { useOutsideDismiss } from "../../../lib/useOutsideDismiss";

export type KeyTableColumn = "station" | "name" | "apiKey" | "group" | "concurrency" | "usage" | "expires" | "status" | "created" | "actions";
export const keyTableColumns: ReadonlyArray<{ key: KeyTableColumn; label: string }> = [{ key: "station", label: "中转站" }, { key: "name", label: "名称" }, { key: "apiKey", label: "API 密钥" }, { key: "group", label: "分组" }, { key: "concurrency", label: "当前并发" }, { key: "usage", label: "用量" }, { key: "expires", label: "过期时间" }, { key: "status", label: "状态" }, { key: "created", label: "创建时间" }, { key: "actions", label: "操作" }];

export function ApiKeyToolbar({ stations, query, station, status, visible, refreshing, showColumns, onQueryChange, onStationChange, onStatusChange, onToggleColumn, onToggleColumns, onCloseColumns, onRefresh, onCreate }: { stations: Station[]; query: string; station: string; status: string; visible: Record<KeyTableColumn, boolean>; refreshing: boolean; showColumns: boolean; onQueryChange: (value: string) => void; onStationChange: (value: string) => void; onStatusChange: (value: string) => void; onToggleColumn: (key: KeyTableColumn) => void; onToggleColumns: () => void; onCloseColumns: () => void; onRefresh: () => void; onCreate: () => void }) {
  const columnMenuRef = useRef<HTMLDivElement>(null);
  useOutsideDismiss(columnMenuRef, showColumns, onCloseColumns);
  return <section className="table-page-toolbar"><div className="table-page-filters"><label className="sub2-search"><Search size={17} /><input value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="搜索密钥名称、站点或分组" /></label><select aria-label="站点筛选" value={station} onChange={(event) => onStationChange(event.target.value)}><option value="all">全部站点</option>{stations.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><select aria-label="状态筛选" value={status} onChange={(event) => onStatusChange(event.target.value)}><option value="all">全部状态</option><option value="active">启用</option><option value="inactive">停用</option></select></div><div className="table-page-actions"><button className="button-secondary" title="刷新" onClick={onRefresh} disabled={refreshing}><RefreshCw size={16} className={refreshing ? "sub2-spin" : ""} /></button><div className="sub2-column-menu" ref={columnMenuRef}><button className="button-secondary" title="列设置" onClick={onToggleColumns}><Columns3 size={16} /><span>列设置</span></button>{showColumns && <div className="sub2-menu">{keyTableColumns.map(({ key, label }) => <label key={key}><input type="checkbox" checked={visible[key]} onChange={() => onToggleColumn(key)} />{label}</label>)}</div>}</div><button className="button-primary" onClick={onCreate}><Plus size={16} />新建密钥</button></div></section>;
}
